model_meta:
  name: SiameseLSTM
  domain: EquationVerificationSequential

model:
  rnn_base: lstm
  d_model: 128
  num_layers: 2
  bidirectional: true
  dropout: 0.3
  similarity_metric: symmetric_bilinear

training:
  batch_size: 128
  learning_rate: 1.0e-3

trainer:
  gradient_clip_val: 1.0
