model_meta:
  name: SiameseTransformer
  domain: EquationVerificationSequential

model:
  d_model: 64
  num_layers: 2
  nhead: 16
  dropout: 0.0

training:
  batch_size: 128
  learning_rate: 1.0e-3

trainer:
  gradient_clip_val: 1.0
