model_meta:
  name: SiameseLSTM

model:
  rnn_base: lstm
  d_model: 64
  num_layers: 2
  bidirectional: true
  dropout: 0.0
  similarity_metric: dot_product

training:
  batch_size: 128
  learning_rate: 1.0e-3

trainer:
  gradient_clip_val: 1.0
