# Train on all of the tasks excluding a primitive, plus just that primitive alone
# (oversampled to be 10% of the dataset). Test on compositions involving that primitive.
# Valid primitives are: jump, turn_left
# NOTE: variants with additional examples are available but not configured.
task:
  name: SCAN
  domain: Seq2Seq
  primitive: turn_left
  train_path: SCAN/add_prim_split/tasks_train_addprim_${task.primitive}.txt
  val_path: SCAN/add_prim_split/tasks_test_addprim_${task.primitive}.txt
