# Use the ~80% shortest sequences (by output length) for training, and the remainder
# for testing.
task:
  name: SCAN
  domain: Seq2Seq
  train_path: SCAN/length_split/tasks_train_length.txt
  val_path: SCAN/length_split/tasks_test_length.txt
