# Train on all of the tasks excluding a "template" (a complex subcommand), then test on
# compositions involving that template.
# Valid templates are: right, opposite_right, around_right, jump_around_right
task:
  name: SCAN
  domain: Seq2Seq
  template: jump_around_right
  train_path: SCAN/template_split/tasks_train_template_${task.template}.txt
  val_path: SCAN/template_split/tasks_test_template_${task.template}.txt
