# Use 80% of the data for training and 20% for testing, split at random.
task:
  name: SCAN
  domain: Seq2Seq
  train_path: SCAN/simple_split/tasks_train_simple.txt
  val_path: SCAN/simple_split/tasks_test_simple.txt
